//! delegate_game — L1 test-harness instruction (Stage 2/3).
//!
//! Delegates Game and Deck to the TEE validator (MTEW…, passed as an argument
//! and asserted against `state::TEE_VALIDATOR`; `validator: None` is never
//! used, matching the smoke program's allowlist pattern). The production
//! `delegate_table` (§11.1) covers all 13 accounts; this harness delegates
//! only the two the VRF path touches. Admin-gated.
//!
//! The `delegate_game`/`delegate_deck` methods are generated by the
//! `#[delegate]` macro from the `del`-marked fields (verified against
//! ephemeral-rollups-sdk-attribute-delegate-0.17.3/src/lib.rs).

use anchor_lang::prelude::*;
use ephemeral_rollups_sdk::cpi::DelegateConfig;

use crate::errors::SolpokerError;
use crate::state::TEE_VALIDATOR;
use crate::DelegateGame;

pub fn handler(ctx: Context<DelegateGame>, validator: Pubkey) -> Result<()> {
    require!(
        validator == TEE_VALIDATOR,
        SolpokerError::ValidatorNotAllowed
    );

    let table_key = ctx.accounts.table.key();
    let table_bytes = table_key.to_bytes();
    let epoch_bytes = ctx.accounts.table.epoch.to_be_bytes();

    ctx.accounts.delegate_game(
        &ctx.accounts.admin,
        &[b"game", table_bytes.as_ref()],
        DelegateConfig {
            validator: Some(validator),
            ..Default::default()
        },
    )?;
    ctx.accounts.delegate_deck(
        &ctx.accounts.admin,
        &[b"deck", table_bytes.as_ref(), &epoch_bytes],
        DelegateConfig {
            validator: Some(validator),
            ..Default::default()
        },
    )?;
    ctx.accounts.delegate_commit_payer(
        &ctx.accounts.admin,
        &[b"commit_payer", table_bytes.as_ref()],
        DelegateConfig {
            validator: Some(validator),
            ..Default::default()
        },
    )?;
    Ok(())
}
